### ISSUE TITLE
OAuth 1.0a support discontinued?

### ISSUE THREAD

**Issue by michaelchart** [Bynder/bynder-c-sharp-sdk#18]
We have been using the OAuth 1.0a authentication with version 1.3 of this SDK. 

We have been using a permanent access token which means we don't need to deal with refreshing expired tokens or any kind of browser redirect flow.

It seems like the latest changes to this SDK have removed support for consumers and permanent access tokens in favour of only supporting the OAuth 2.0 implementation.

If the OAuth 2.0 implementation is the way forwards, then how would this be used in a purely server-side scenario where an application is accessing the Bynder API but there is no user interaction or browser involved? Do we now need to deal with refreshing access tokens too?

**Comment by danielsequeira** [comment]
Hi @michaelchart,

Yes for the newest release/tag 2.0.0 of the SDK OAuth 1.0a support was removed, this new release only supports OAuth 2.0.

This is due to the fact that in the long term we do want to deprecate OAuth 1.0a in Bynder and only use OAuth 2.0. At the moment we don't have an official plan or timeline for the deprecation, which might still take a while.

In the meantime to still make use of OAuth 1.0a, you will need to use one of the previous releases/tags.

Regarding server-to-server communication we just finished implementing permanent tokens functionality for our OAuth2 service. And at the moment we are adding this functionality to all our SDKs, what should be finished some time during next weel.

For now you can indeed use refresh tokens which are permanent and can be used to generate new access tokens. This logic is already implemented in the SDK as well, which will automatically refresh the token if it expired and there's a refresh token available.

https://github.com/Bynder/bynder-c-sharp-sdk/blob/master/Bynder/Sdk/Settings/Credentials.cs#L86

**Comment by michaelchart** [comment]
Hi @danielsequeira,

It sounds like the server-to-server permanent tokens for OAuth2 are what we need. We'll look to migrate to use these when this becomes available in the SDK, which sounds like it might be in the couple of weeks.

Thanks!
