### ISSUE TITLE
FS_upload_dev branch missing fields on upload

### ISSUE THREAD

**Issue by Shiqan** [Bynder/bynder-c-sharp-sdk#79]
While adding some missing features to the api in my [fork](https://github.com/Shiqan/bynder-c-sharp-sdk/tree/feature/stream-upload) (such as upload directly from a stream and metaproperty endpoints) I noticed that the [FS_upload_dev](https://github.com/Bynder/bynder-c-sharp-sdk/tree/FS_upload_dev) branch I've been using as a base results in some fields not being populated on upload.

Upload through filepath on master:
```json
{
   "height": 2880,
   "fileSize": 1574336,
   "width": 4095
}
``` 

Upload through filepath on FS_upload_dev:
```json
{
   "height": 0,
   "fileSize": 0,
   "width": 0
}
``` 

So these three fields are missing in the api response when retrieving media (`{{base_url}}/api/v4/media/{{mediaId}}`).
In the portal UI itself there are more fields missing: `copyright`, `author` and `resolution`. Where the latter two cannot even be set at all.

Is this a result from the more direct upload to S3 that is skipping a process on Bynders end?
And is there anything that can be done to fix this?

**Comment by meghuizen** [comment]
I suspect the direct upload approach is not yet fully working enough to be used in production. Though it's really quiet on this on Bynder's end. Not sure what's happening with this direct flow.

I also can't wait to use the direct file upload flow, since the async indirect one (with the polling) gives us a lot of instability.
